export * from '../build/extend-expect';

// This directory exists to work around https://github.com/microsoft/TypeScript/issues/33079
// and similar issues with other tooling

// note that this file is NOT auto-generated by the build process!
// (due to https://github.com/davidje13/neutrino-typescript/issues/6)
